repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml # checks yaml files for parseable syntax.
    -   id: check-added-large-files
    -   id: check-merge-conflict # checks for files that contain merge conflict strings.
    -   id: check-toml # checks toml files for parseable syntax.

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  # - repo: https://github.com/psf/black
  #   rev: 22.3.0
  #   hooks:
  #     - id: black
  #       exclude: ^(migrations/|contrib/|templates/)

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: 71cd8ff86aa4dd50210ba4d86a9ff5dc6339e9a0
    hooks:
      - id: docker-compose-check # Checks that docker-compose files are valid


  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: df034f88cf92b394e6f00a78fa97a2aa4e270e60
    hooks:
    -   id: check-poetry # Validates the structure of the pyproject.toml file

  - repo: local
    hooks:
      - id: unittests
        name: Run unit tests
        entry: python manage.py test
        language: system
        pass_filenames: false
