# Generated by Django 3.2.12 on 2022-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_alter_newsletterlanguage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Define if the project is active'),
        ),
    ]
