# Generated by Django 3.2.15 on 2022-09-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_templateproject_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='trial_end_date',
            field=models.DateTimeField(null=True, verbose_name='Trial end date'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('trial', 'trial'), ('enterprise', 'enterprise'), ('custom', 'custom')], max_length=10, verbose_name='plan'),
        ),
    ]
