# Generated by Django 3.2.15 on 2022-10-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0061_auto_20220928_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('trial', 'trial'), ('basic', 'basic'), ('plus', 'plus'), ('premium', 'premium'), ('enterprise', 'enterprise'), ('custom', 'custom')], max_length=10, verbose_name='plan'),
        ),
    ]
